spring:
  application:
    name: BackEnd
  datasource:
    url: mysql://sp5d5dirntj8h8rs:dvx5cf3yj02ffb85@d6vscs19jtah8iwb.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/v9mw6t8md0s40uqm
    username: sp5d5dirntj8h8rs
    password: dvx5cf3yj02ffb85
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 372091179984-l3inopvggus0e2hn0h91hq9tes0m6a9u.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          facebook:
            client-id: 722531733585802
            client-secret: 002132a9226cb1f7ad88aa6c09c84914
            scope: email, public_profile
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook