spring:
  application:
    name: BackEnd
  datasource:
    url: jdbc:${JAWSDB_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
            scope: ${SCOPE_GOOGLE}
            redirect-uri: ${REDIRECT_URL_GOOGLE}
          facebook:
            client-id: ${CLIENT_ID_FACEBOOK}
            client-secret: ${CLIENT_SECRET_FACEBOOK}
            scope: ${SCOPE_FACEBOOK}
            redirect-uri: ${REDIRECT_URI_FACEBOOK}
server:
  port: ${PORT:8080}
